# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2022-05-18 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='主題')),
                ('note', models.TextField()),
                ('b_time', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('c_time', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
                ('bparticlenum', models.ManyToManyField(related_name='bparticlenum', to='index.Backpacker', verbose_name='文章編號')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'favorite',
            },
        ),
    ]
