# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2022-05-18 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backpacker',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('articlenum', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('reports', models.CharField(blank=True, max_length=20, null=True)),
                ('b_time', models.DateTimeField(blank=True, null=True)),
                ('c_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'backpacker',
                'managed': False,
            },
        ),
    ]
