# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2022-05-18 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='使用者名稱')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='電子郵件')),
                ('password', models.CharField(max_length=32, verbose_name='密碼')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
